const ETAPAS = Object.freeze({
  ARRANQUE: 'ARRANQUE',
  RECEPCION: 'RECEPCION',
  PARSEO_JSON: 'PARSEO_JSON',
  VALIDACION_ESQUEMA: 'VALIDACION_ESQUEMA',
  VALIDACION_HASH: 'VALIDACION_HASH',
  DUPLICADOS: 'DUPLICADOS',
  USUARIO: 'USUARIO',
  ORDENAMIENTO: 'ORDENAMIENTO',
  VENTANA_DESLIZANTE: 'VENTANA_DESLIZANTE',
  PERSISTENCIA: 'PERSISTENCIA',
  CONSULTA: 'CONSULTA',
  CONFIGURACION: 'CONFIGURACION',
  RESPUESTA: 'RESPUESTA',
});

module.exports = { ETAPAS };
